name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v6
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v3
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Validate Azure ML settings
      shell: bash
    - name: Run Azure Machine Learning training job
      run: az ml job create -f src/job.yml --stream --resource-group "${RESOURCE_GROUP}" --workspace-name "${WORKSPACE_NAME}"